language: cpp
before_script:
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - echo "deb http://archive.ubuntu.com/ubuntu xenial main universe" | sudo tee -a /etc/apt/sources.list    
    - sudo apt-get update -qq
    - sudo apt-get -y install gcc-6 g++-6 libboost-test-dev cmake doxygen graphviz -y
    - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 90
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90  
#    - sudo apt-get update -qq
#    - sudo apt-get install libspdlog-dev -y
script:
  - cmake .
  - cmake --build . -- VERBOSE=1
#  - cmake --build . --target test
  - cmake --build . --target package
  - doxygen doxygen.cfg
deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
    keep-history: true
    on:
        branch: master
    provider: script
    skip_cleanup: true
    script:
    - curl -T print_ip-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -uEast-Oz:$BINTRAY_API_KEY "https://api.bintray.com/content/east-oz/otus-cpp/OtusHomeworks/$TRAVIS_BUILD_NUMBER/print_ip-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"
